export const BRAND = {
  BUSINESS_NAME: "Irving The AC Man",
  LEGAL_NAME: "Irving The AC Man LLC",
  OWNER: "Irving Hernandez",
  TAGLINE: "South Florida's Most Trusted AC Expert",
  PHONE: "9542921208",
  PHONE_DISPLAY: "(954) 292-1208",
  EMAIL: "irvingtheacman@gmail.com",
  ADDRESS: "5031 NE 6th Ave, Pompano Beach, FL 33064",
  CITY: "Pompano Beach",
  STATE: "FL",
  ZIP: "33064",
  LICENSE: "CAC1821029",
  YEARS_EXPERIENCE: "17+",
  REVIEW_COUNT: "100+",
  RATING: "5.0",
  HOURS: "Available 24/7 — Including Weekends & Holidays",
  EMERGENCY_TEXT: "Same-Day Emergency Service Available",
  GOOGLE_MAPS_URL: "https://www.google.com/maps/place/IRVING+THE+AC+MAN",
  GOOGLE_MAPS_EMBED: "", // add real embed URL after getting from client
  BRANDS_SERVICED: ["Trane", "Carrier", "Rheem", "Goodman", "Lennox", "York"],
  SERVICES: [
    "Emergency / Same-Day Service",
    "AC Repair & Diagnostics",
    "New AC Installation",
    "Preventive Maintenance",
    "Commercial HVAC",
    "Duct Cleaning",
  ],
  SERVICE_AREA: [
    "Pompano Beach", "Deerfield Beach", "Lighthouse Point",
    "Boca Raton", "Delray Beach", "Fort Lauderdale",
    "Coral Springs", "Coconut Creek", "Margate", "Tamarac",
    "Oakland Park", "Wilton Manors", "Lauderdale-by-the-Sea",
    "Hillsboro Beach", "North Lauderdale", "Lauderdale Lakes",
    "Plantation", "Davie", "Weston", "Hollywood",
  ],
  COLORS: {
    primary: "oklch(60% 0.18 220)",
    navy: "oklch(15% 0.04 264)",
    emergency: "oklch(80% 0.18 70)",
  },
  NETLIFY_FORM_NAME: "irving-acman-leads",
} as const
